<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLxylEzQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLxylEzQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLxylEzQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLxylEzQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLxylEzQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'LxylEzQ',
    'container.build_id' => 'f4707573',
    'container.build_time' => 1701853637,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLxylEzQ');
